version: '3.8'

services:
  backend:
    # ATENÇÃO: Substitua 'SEU_USUARIO_DOCKERHUB' pelo seu nome de usuário
    image: SEU_USUARIO_DOCKERHUB/trabalho-backend:1.0
    ports:
      - "3000:3000"
    networks:
      - app-net

  frontend:
    # ATENÇÃO: Substitua 'SEU_USUARIO_DOCKERHUB' pelo seu nome de usuário
    image: SEU_USUARIO_DOCKERHUB/trabalho-frontend:1.0
    ports:
      - "8080:80"
    networks:
      - app-net

networks:
  app-net:
    driver: overlay