version: '3.8'
services:
  backend:
    # A linha 'build' foi removida
    image: pedrobachaalani1701/meu-projeto-backend:1.0 # Modificada
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      # Adicionado para garantir que o backend espere o DB
      - DATABASE_URL=postgres://user:password@db:5432/postgres

  frontend:
    # A linha 'build' foi removida
    image: pedrobachaalani1701/meu-projeto-frontend:1.0 # Modificada
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: overlay # Especificar o driver overlay é uma boa prática