version: '3.8'
services:
  backend:
    build: ./backend
    image: minha_stack_backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: minha_stack_frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
